### PR TITLE
Added Split-versioning Functionality to Backend

### PR DESCRIPTION
**Pull request by kylanerace**
## Proposed changes

- Added frontend version file
- Updated import-library util to handle split-versioning of api-bridge/frontend

## Types of changes

What types of changes does your code introduce to the HEBench Cleartext Reference Backend?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/hebench/backend-cpu-cleartext/blob/main/CONTRIBUTING.md) doc
- [x] Current formatting and unit tests / base functionality passes locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

N/A

### CODE REVIEW

**Comment by sidezrw** [comment]
Why, during CMake run in the build, API_BRIDGE component is listed twice? See below:

```
-- ===== Configuring Third-Pary: API_BRIDGE =====
-- Required API_BRIDGE Version: v0.5.1-beta
-- Required FRONTEND Version: v0.5.1-beta
-- API_BRIDGE_INCLUDE_DIR: /usr/local/include
-- API_BRIDGE_LIB_DIR: /usr/local/lib
-- No user-defined paths (-DAPI_BRIDGE_[INSTALL|INCLUDE|LIB]_DIR) were set
-- API_BRIDGE could not be found at the default location
-- Downloading and Installing it...
-- CMAKE_BUILD_TYPE: Release
-- Project Version: v0.5.1-beta
-- HIDE_EXT_WARNINGS: OFF
-- CMAKE_INSTALL_PREFIX /home/runner/work/backend-cpu-cleartext/backend-cpu-cleartext/build
-- ===== Configuring Third-Pary: API_BRIDGE =====
-- Required Version: v0.5.1-beta
-- API_BRIDGE_INCLUDE_DIR: /usr/local/include
-- API_BRIDGE_LIB_DIR: /usr/local/lib
-- No user-defined paths (-DAPI_BRIDGE_[INSTALL|INCLUDE|LIB]_DIR) were set
-- API_BRIDGE could not be found at the default location
-- Downloading and Installing it...
-- CMAKE_BUILD_TYPE: Release
-- Project Version: v0.5.1-beta
-- CMAKE_INSTALL_PREFIX /home/runner/work/backend-cpu-cleartext/backend-cpu-cleartext/build
```

**Comment by sidezrw** [comment]
Is this because the first API_BRIDGE is actually the frontend, and the second is printed out by frontend CMake?

**Review by sidezrw — APPROVED** [review]
Looks good.

**Comment by kylanerace** [comment]
> 



> Is this because the first API_BRIDGE is actually the frontend, and the second is printed out by frontend CMake?

Correct, you're exactly right.

**Pull request merged**
